version: "3"

services:
  api:
    build: ./server
    env_file:
      - ./server/.env
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://db/db_001
    ports:
      - "5000:5000"
    depends_on:
      - db
    container_name: server

  client:
    build: ./client
    ports:
      - "85:80"
    container_name: client

  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: db